name: sapling-demo
region: syd
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: kgrwhite/sapling
    source_dir: /sapling-demo
    build_command: npm run build
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production